### ISSUE TITLE
Lasso CLI doesn't compile on Node 0.12 and above

### ISSUE THREAD

**Issue by kprakasam** [lasso-js/lasso-cli#4]
```
> fsevents@0.2.1 install /usr/local/lib/node_modules/lasso-cli/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:339:13: error: no member named 'New' in 'v8::String'
    return  _NAN_ERROR(v8::Exception::Error, errmsg);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../node_modules/nan/nan.h:343:5: error: no member named 'ThrowException' in namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:324:11: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
      ~~~~^
```

**Comment by tbashor** [comment]
+1

**Comment by patrick-steele-idem** [comment]
Sorry for not being able to take a look at this sooner. I will take a look at it now and see if I can put in a quick fix. Worst case, I will have a fix in early next week, but hopefully I can get it working today. Thanks for reporting the problem.

**Comment by patrick-steele-idem** [comment]
I published a new version of the `lasso-cli` package that is now compatible with all versions of Node.js:

```
npm install lasso-cli@^1.1.16 --global
```

Please let me know if you still see issues. Thanks!
